server:
  port: 8001

spring:
  application:
    name: human-resource-worker  datasource:    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:    console:      enabled: true
      path: /h2-console